- hosts: pi4
  become: true
  vars_files:
    - vars/default.yml
  tasks:
    - name: Install latest version of Apache
      apt: name=apache2 update_cache=yes state=latest

    - name: Create document root for your domain
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Copy your index page
      template:
        src: "templates/index.html.j2"
        dest: "/var/www/{{ http_host }}/index.html"

    - name: Set up virtualHost
      template:
        src: "templates/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: restart-apacheo

    - name: link as available site
      file:
        src: "/etc/apache2/sites-available/{{ http_conf }}"
        dest: "/etc/apache2/sites-enabled/{{ http_conf }}"
        state: link

  handlers:
    - name: restart-apache
      service:
        name: apache2
        state: restarted
