- hosts: pis
  become: true
  become_user: root
  tasks:
    - name: install python dependencies
       apt:
        name: python3-dev
        state: present
        update_cache: yes
    - name: create an account
      ansible.builtin.user:
        name: homeassistant
