- hosts: pis
  become: true
  become_user: root
  tasks:
     - name: install python dependencies
       apt:
        name:
          - python3-dev python3-venv python3-pip bluez libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 libturbojpeg0-dev tzdata
        state: present
        update_cache: yes