- hosts: pis
  become: true
  become_user: root
  tasks:
    - name: install python dependencies
      apt:
        name: python3-dev, python3-venv, python3-pip, bluez, libffi-dev, libssl-dev, libjpeg-dev, zlib1g-dev, autoconf, build-essential, libopenjp2-7, libtiff6, libturbojpeg0-dev, tzdata, libpcap0.8-dev
        state: present
        update_cache: yes
    - name: create group
      ansible.builtin.group:
        name: homeassistant
        state: present
    - name: create an account
      ansible.builtin.user:
        name: homeassistant
        group: homeassistant
        groups: dialout,gpio, i2c
    - name: create install home dir
      file:
        path: /srv/homeassistant
        state: directory
        owner: homeassistant
        group: homeassistant
    - name: install virtual env
      pip:
        name: virtualenv, wheel
    - name: virtual install
      pip:
        virtualenv: /srv/homeassistant
        virtualenv_python: python3.9
        name: wheel, homeassistant
    - name: run hass
      shell: nohup bin/hass </dev/null >/dev/null 2>&1 &
      args:
        chdir: /srv/homeassistant
    - name: wget home automation community
      ansible.builtin.get_url:
        url: https://get.hacs.xyz
        dest: /srv/homeassistant
        username: homeassistant