- hosts: pis
  become: true
  become_user: root
  tasks:
    - name: install python dependencies
      apt:
        name: python3-dev, python3-venv, python3-pip, bluez, libffi-dev, libssl-dev, libjpeg-dev, zlib1g-dev, autoconf, build-essential, libopenjp2-7, libtiff5, libturbojpeg0-dev, tzdata
        state: present
        update_cache: yes
    - name: create an account
      ansible.builtin.user:
        name: homeassistant
        group: homeassistant
        groups: dialout,gpio, i2c
    - name: create install home dir
      file:
        path: /srv/homeassistant
        state: directory
        owner: homeassistant
        group: homeassistant
    - name: install virtual env
      pip:
        name: virtualenv, wheel
    - name: virtual install
      pip:
        virtualenv: /srv/homeassistant
        virtualenv_python: python3.9
        name: wheel, homeassistant
    -name: run hass
      shell: hass
      args:
        chdir: /srv/homeassistant