- hosts: pi4
  become: true
  become_user: root
  tasks:
  - name: Get stuff from git
    git:
      repo: https://github.com/micropython/micropython.git
      dest: /var/opt/micropython
      clone: yes
      update: yes
      force: yes
#https://forums.raspberrypi.com/viewtopic.php?t=191744
