- hosts: pis
  become: true
  become_user: root
  tasks:
  - name: install using pip
    pip:
      name: botocore,boto3,esptool,rshell
  - name: install twitter reader twython using pip
    pip:
      name: twython 
