---
- name:
  apt:
    name: libc6:arm64
    state: present
    
- name: Download the awscli bundle.
  get_url: url=https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip dest=/tmp/awscli-bundle.zip
  register: aws_cli_download_bundle

- name: Unarchive the installer.
  unarchive: src=/tmp/awscli-bundle.zip dest=/tmp copy=no
  when: aws_cli_download_bundle.changed
  register: aws_cli_unarchive_installer

- name: Install awscli package.
  shell:  /tmp/aws/install -i /usr/local/aws-cli -b /usr/local/bin
  args:
    creates: /usr/local/bin/aws
  when: aws_cli_unarchive_installer.changed

- name: Configure AWS.
  shell: aws configure set {{ item.key }} {{ item.value }} --profile {{ aws_profile }}
  with_dict:
    aws_access_key_id: "{{ aws_access_key }}"
    aws_secret_access_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    format: "{{ aws_format }}"
  become_user: "{{ aws_system_user }}"
  changed_when: false

- name: Cleanup.
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - /tmp/aws
    - /tmp/awscli-bundle.zip